# Generated by Django 4.1.3 on 2023-02-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raza',
            name='precio',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
